language: php

notifications:
  email:
    recipients:
      - daniel.roperto@catalyst-au.net

sudo: required

addons:
  firefox: "35.0.1"
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 5.6
  - 7.0

env:
  global:
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_31_STABLE
    # - MOODLE_BRANCH=MOODLE_32_STABLE
    # - MOODLE_BRANCH=MOODLE_33_STABLE
    # - MOODLE_BRANCH=master

matrix:
  include:
    # Test PHP 5.6
    # - php: 5.6
    #   env: MOODLE_BRANCH=MOODLE_31_STABLE
    # Test PHP 7.1
    # - php: 7.1
    #   env: MOODLE_BRANCH=master
    # Test MySQL
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - if [ "$MOODLE_VERSION" = "master" ] || [ "$MOODLE_VERSION" -ge 32 ]; then export CI=2; else export CI=1; fi
  - echo $CI
  - phpenv config-rm xdebug.ini
  - nvm install node
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^$CI
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker

  - if [ "$CI" -eq 1 ]; then moodle-plugin-ci csslint    ; fi
  - if [ "$CI" -eq 1 ]; then moodle-plugin-ci jshint     ; fi
  - if [ "$CI" -eq 1 ]; then moodle-plugin-ci shifter    ; fi

  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci savepoints ; fi
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci mustache   ; fi
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci grunt      ; fi

  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
